name: universal_boilerplate_mvc
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  bloc: ^9.0.0
  flutter_bloc: ^9.1.1
  hydrated_bloc: ^10.1.1
  path_provider: ^2.1.5
  go_router: ^16.2.1
  intl: ^0.20.2
  flutter_localizations:
    sdk: flutter
  dynamic_path_url_strategy: ^1.0.0
  window_manager: ^0.5.1
  stylish_bottom_bar: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  generate: true # Enables generation of localization files
  uses-material-design: true
